apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "5"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"captureorder"},"name":"captureorder-deployment","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"captureorder"}},"template":{"metadata":{"labels":{"app":"captureorder"}},"spec":{"containers":[{"env":[{"name":"MONGOHOST","value":"mongodb://team4:team4@left-hedgehog-mongodb/team4"},{"name":"TEAMNAME","value":"team4"},{"name":"RABBITMQHOST","value":"amqp://rabbitmq:rabbitmq@ulterior-labradoodle-rabbitmq:5672"}],"image":"shanepeckham/captureorderack:v5","name":"captureorder","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: 2018-02-15T10:45:22Z
  generation: 5
  labels:
    app: captureorder
  name: captureorder-deployment
  namespace: default
  resourceVersion: "93857"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/captureorder-deployment
  uid: 52c271d1-123d-11e8-9a1f-000d3a13c563
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: captureorder
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: captureorder
    spec:
      containers:
      - env:
        - name: MONGOHOST
          value: mongodb://team4:team4@left-hedgehog-mongodb/team4
        - name: TEAMNAME
          value: team4
        - name: RABBITMQHOST
          value: amqp://rabbitmq:rabbitmq@ulterior-labradoodle-rabbitmq:5672
        image: shanepeckham/captureorderack:v5
        imagePullPolicy: IfNotPresent
        name: captureorder
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: 2018-02-15T10:45:22Z
    lastUpdateTime: 2018-02-15T12:16:11Z
    message: ReplicaSet "captureorder-deployment-994735272" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-02-16T02:19:20Z
    lastUpdateTime: 2018-02-16T02:19:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
