---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: captureOrder-deployment
  labels:
    app: captureOrder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: captureOrder
  template:
    metadata:
      labels:
        app: captureOrder
    spec:
      containers:
      - name: captureOrder
        image: shanepeckham/captureorderack:v5
        ports:
        - containerPort: 80
